name: Test

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
      - name: 'pyenv'
        run: curl https://pyenv.run | bash
      - name: 'install python'
        run: $HOME/.pyenv/bin/pyenv install 3.10
      - name: 'install poetry'
        run: |
          export POETRY_HOME=/opt/poetry
          curl -sSL https://install.python-poetry.org | python3.10 -
      - name: 'poetry version'
        run: /opt/poetry/bin/poetry --version
