name: Test

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
      - name: 'pyenv'
        run: curl https://pyenv.run | bash
